name: Docker Image CI

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    
env: 
  IMAGE_NAME: asa-samples/web
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get current git tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.2
      with:
        strip_v: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
    
