name: Docker Image CI

on:
  push:
    tags: ['v*.*.*']
    
env: 
  IMAGE_NAME: asa-samples/web
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: ./mvnw clean package
    - name: Get current git tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.2
      with:
        strip_v: true
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        build-args: 
          version=${{ steps.tag.outputs.tag }}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
    
